### ISSUE TITLE
Extend the list of packages contained in pyroll-basic

### ISSUE THREAD

**Issue by RichardPfr** [pyroll-project/pyroll-basic#2]
We should again go through the list of packages and which of those should be included in the pyroll-basic package.

In recent dicussions for example the pyroll-pillar-model was mentioned.

> [!NOTE]
> Please use this issue for tracking the addition of those packages. See [here](https://github.com/orgs/pyroll-project/discussions/218) for discussions on what to change or include

**Comment by ChRen95** [comment]
Added linear thermal expansion further no packages are necessary.
